# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseURL = "https://fbez.github.io/workshop-esp-idf/"
title = "Espressif ESP-IDF Workshops"


buildDrafts = false
buildFuture = true

[services]
  [services.googleAnalytics]
    id = "G-K9NTMXPGN3"
